### ISSUE TITLE
SMTP AUTH extension not supported by server non-STARTLS/25

### ISSUE THREAD

**Issue by denji** [getsentry/docker-sentry#101]
> SMTP AUTH extension not supported by server

Suggestions for correcting the problem
----------------------------------------

* https://tools.ietf.org/html/rfc6409
* https://tools.ietf.org/html/draft-ietf-yam-rfc4409bis-03
* Plaintext auth method needs to be declared obsolete 
  * Use `STARTLS` to transfer in an insecure SMTP environment `port:25/587`
  * Use `TLS`  to transfer in an secure SMTP environment `port:587`

/etc/dovecot/conf.d/10-auth.conf
----------------------------------

     disable_plaintext_auth = yes
     auth_mechanisms = plain login
     !include auth-sql.conf.ext

/etc/postfix/main.cf
--------------------

     ####################
     ## TLS PARAMETERS ##
     ####################
     smtpd_tls_auth_only           = yes
     smtpd_tls_security_level      = may
     smtpd_tls_received_header     = yes
     smtpd_tls_protocols           = !SSLv2, !SSLv3
     smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
     smtpd_tls_mandatory_ciphers   = medium
     smtpd_tls_exclude_ciphers     = aNULL,eNULL,EXPORT,DES,3DES,RC2,RC4,MD5,PSK,SRP,DSS,AECDH,ADH

     #####################
     ## SASL PARAMETERS ##
     #####################
     smtpd_sasl_auth_enable          = yes
     smtpd_sasl_type                 = dovecot
     smtpd_sasl_path                 = private/auth
     smtpd_sasl_security_options     = noanonymous
     smtpd_sasl_tls_security_options = $smtpd_sasl_security_options
     smtpd_sasl_local_domain         = $mydomain
     smtpd_sasl_authenticated_header = yes
     broken_sasl_auth_clients = yes

**Comment by mattrobenolt** [comment]
Hm? What's the issue or concern here for Sentry?

**Comment by mattrobenolt** [comment]
To be clear, we support TLS.

**Comment by denji** [comment]
Migrated to platform solution LGTM https://github.com/atech/postal

**Comment by uhlhosting** [comment]
@denji you got this working with postal? Can you provide details?

**Comment by BYK** [comment]
@uhlhosting please use the forums for custom configuration discussions: https://forum.sentry.io/c/on-premise
