### ISSUE TITLE
Config SENTRY_FEATURES through environment variables?

### ISSUE THREAD

**Issue by ushuz** [getsentry/docker-sentry#104]
By adding following lines to `sentry.conf.py`, one can config `SENTRY_FEATURES` through environment variables. Thus, no need to override config files to disable registration or to change other features. Thoughts?

```python
for k in SENTRY_FEATURES.keys():
    v = env('SENTRY_FEATURES_{}'.format(k.replace(':', '_').replace('-', '_').upper()))
    if v:
        SENTRY_FEATUES[k] = v.lower() in ['true', '1', 'yes', 'y']
```

**Comment by mattrobenolt** [comment]
Please feel free to add this to your own installation. We are not trying to solve every problem here out of the box.

**Comment by pavel-khritonenko** [comment]
@ushuz you have a typo in 4th line of your script. Thx, it was very helpful.

**Comment by goroi** [comment]
I think in case you want to have extra features or changes added to sentry.conf.py the best is to use the "onbuild" image and then track all your changes in git.
