### ISSUE TITLE
sentry empty database setup failed

### ISSUE THREAD

**Issue by huang475** [getsentry/docker-sentry#105]
When I run `docker run -it --rm -e SENTRY_SECRET_KEY=***  ...{some pg and redis env}...  sentry upgrade`,  I got some error like `[ERROR] sentry.errors: Unable to fetch internal project` `sentry.exceptions.InvalidConfiguration: invalid DB index`.

**Comment by Twister915** [comment]
I am having this same issue

**Comment by huang475** [comment]
@Twister915 you are right

**Comment by gregwym** [comment]
It happened to me as well. Turns out I shouldn't specify the env variable `SENTRY_REDIS_DB`.
