### ISSUE TITLE
Support SENTRY_DISABLE_AUTH_REGISTER environment variable

### ISSUE THREAD

**Issue by ushis** [getsentry/docker-sentry#108]
Hey,

it would be super cool, to disable the registration feature via environment variable. Please add something like this to *sentry.conf.py*:

```python
SENTRY_FEATURES['auth:register'] = not env('SENTRY_DISABLE_AUTH_REGISTER', False)  
```

Thx, ushi

**Comment by mattrobenolt** [comment]
In the 8.18, this will be configurable from the UI.
