### ISSUE TITLE
 Sentry docs outdated?

### ISSUE THREAD

**Issue by jean** [getsentry/docker-sentry#110]
1. The initial `upgrade` doesn't prompt to create a user (I created one using `createuser`).
2. web access fails:

```
14:15:21 [ERROR] django.request: Internal Server Error: /auth/login/ (status_code=500 request=<WSGIRequest
path:/auth/login/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'sentrysid': 'gAJ9cQFVBV9uZXh0cQJYAQAAAC9zLg:1da0cL:oheX1okO8EtfQMhngEkclzPpRp8'},
META:{u'CSRF_COOKIE': u'mW7mLInhWIsqZbQhaYlIQhZAeOeUr8dF',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'identity',
 'HTTP_CONNECTION': 'Keep-Alive',
 'HTTP_COOKIE': 'sentrysid="gAJ9cQFVBV9uZXh0cQJYAQAAAC9zLg:1da0cL:oheX1okO8EtfQMhngEkclzPpRp8"',
 'HTTP_HOST': 'localhost:9000',
 'HTTP_USER_AGENT': 'Wget/1.17.1 (linux-gnu)',
 'PATH_INFO': u'/auth/login/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '172.17.0.1',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/auth/login/',
 'SCRIPT_NAME': u'',
 'SERVER_NAME': 'f2ac594e246c',
 'SERVER_PORT': '9000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'uwsgi.core': 3,
 'uwsgi.node': 'f2ac594e246c',
 'uwsgi.version': '2.0.15',
 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x7f77265a7780>,
 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>,
 'wsgi.input': <uwsgi._Input object at 0x7f77241d7360>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/error_500.py", line 22, in get_embed_config
    )[0]
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
14:15:21 [ERROR] root: Unable to fetch ProjectKey for internal project
14:15:21 [ERROR] sentry.errors: Internal project (id=1) does not exist
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/templatetags/sentry_react.py", line 67, in _get_public_dsn
    )[0]
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
14:15:21 [ERROR] root: Unable to fetch ProjectKey for internal project
14:15:21 [ERROR] sentry.errors: Internal project (id=1) does not exist
172.17.0.1 - - [25/Jul/2017:14:15:21 +0000] "GET /auth/login/ HTTP/1.1" 500 8631 "-" "Wget/1.17.1 (linux-gnu)"
```

This was after following https://github.com/docker-library/docs/tree/master/sentry step by step. 

(Moved here in response to https://github.com/docker-library/docs/issues/967#issuecomment-319224835)

**Comment by jean** [comment]
I see that these docs are referenced from https://docs.docker.com/samples/sentry/ which is out of date (e.g. referring to `8.14` and `8.15`, instead of `8.17` and `8.18`). How do those docs get updated?

**Comment by aemino** [comment]
I'm having the exact same issue using the Sentry stack from the Rancher Catalog.

**Comment by matti** [comment]
I'm seeing this too with my attempt to create my own docker-compose.yml, BUT following docker docs eg. forking sentry-onpremise etc works.

**Comment by matti** [comment]
I'm 99% sure it has to do with the migration being not run until the very end where. Now when I carefully re-run everything it went fine.

**Comment by matti** [comment]
Btw, the initial upgrade prompts for user creation unless you have specified. This is how I roll:

```
    /entrypoint.sh upgrade --noinput --lock
    /entrypoint.sh createuser --email=lol@lol.com --password=lolol --superuser --no-input
```

**Comment by jean** [comment]
@matti , awesome, thanks for the notes, I'll give it a try again tomorrow. How do you "carefully rerun", do you type one key at a time? (Just kidding, but I did try and go step by step from scratch.)

**Comment by matti** [comment]
Just made sure that the migration finishes (check the output, it mist say that the sentry internal project was made)

**Comment by matti** [comment]
I'm pretty sure my error was running out of memory. Migrations just stop at some point when that happen.

**Comment by chadyred** [comment]
Same here !

**Comment by mattrobenolt** [comment]
Closing this because nothing is documented incorrectly. People are just OOMing.

**Comment by tuxick** [comment]
Maybe in some cases it's OOM problem, but definitely not in my case.  Upgrade completed without complaints. And even if it's OOM, "IndexError: list index out of range" isn't really the way to handle this.

**Comment by Wirone** [comment]
Today I've been struggling with this OOM issue and @matti's tip (`--noinput`) helped me... with additional `htop` and `kill` :joy: But before that I've been trying about 10 times from scratch... Finally it's working and I can configure everything :)
