### ISSUE TITLE
on armhf architecture, libsourcemap package asks for clang

### ISSUE THREAD

**Issue by athoune** [getsentry/docker-sentry#112]
Because no wheel are available on pipy. OK, armhf are a bit exotic.

Adding and removing `clang` debian package, just like `g++` fix the error.

**Comment by athoune** [comment]
OMG, it needs Rust. It must be easier ta ask for arm wheels.

**Comment by mattrobenolt** [comment]
Yeah, sentry won't run on ARM. We document this explicitly somewhere. We distribute wheels for the platforms we're compatible with.

What is your use case?
