### ISSUE TITLE
Overly specific FROM "python:2.7.13-slim" is no longer supported

### ISSUE THREAD

**Issue by tianon** [getsentry/docker-sentry#116]
The current 8.19 and 8.20 tags of the `sentry` official image are both `FROM python:2.7.13-slim`, which is overly specific and given newer Python 2.7 releases, no longer a supported tag (and thus no longer receiving base image triggered rebuilds, including and especially security updates).

I would recommend replacing these overly-specific versions with simply `FROM python:2.7-slim`, which will stay supported as long as the 2.7 series of Python still is. :+1:

**Comment by mattrobenolt** [comment]
Yeah, I'll bump this to 2.7.14 in next release. We prefer to explicitly pin our python version since we're python snobs and pair it with what we run ourselves in production.

**Comment by mattrobenolt** [comment]
This is getting bumped in aefb6c14b1209040a33d5cbbe8ead5b9facb09d4 to 2.7.15, which will propagate into 9.0 builds.
