### ISSUE TITLE
Bundle LDAP Auth plugin

### ISSUE THREAD

**Issue by Fank** [getsentry/docker-sentry#122]
I would be nice to include the ldap auth plugin by default, and maybe some other like Github/Gitlab too.
And control them via environment variables, or docker secrets like in https://github.com/slafs/sentry-docker/blob/master/README.md#available-environment-variables

**Comment by mattrobenolt** [comment]
It’s unlikely we’ll bundle LDAP since the plugin is not officially from us. We make it super easy to install additional plugins. 

And we already do bundle all of [sentry-plugins](https://github.com/getsentry/sentry-plugins) which contains both GitHub and Gitlab.

**Comment by Fank** [comment]
In a docker swarm environment, you don't have persistent storage. So you can't do something like `pip install ...` because if the docker service changes the container will be deleted and recreated by swarm.
So i need a image which contains everything, so i can enable it or not.

Currently the only work arround will be forking this repo and maintaining it to keep it up2date. Which is very annoying. So it would be quite nice to create a new tag which contain all nice things or add them in the default tag.

**Comment by mattrobenolt** [comment]
I understand, but the instructions explain about creating your own images. We can’t install everything, and like I said, we don’t maintain the LDAP plugin. So if we start bundling it with Sentry, that means we need to assume responsibility if it’s broken and test releases with it, which we aren’t prepared to do.

Just build your own image and save it in your own registry. This is pretty common practice for lots of software. See: https://github.com/getsentry/onpremise

This is why we maintain `onbuild` variants of our images to be built on top of.

**Comment by yosifkit** [comment]
With automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links) it's reasonably easy to have an up-to-date image built `FROM` this one with this additional functionality added.
