### ISSUE TITLE
Sentry docker on kubernetes stop uWSGI 

### ISSUE THREAD

**Issue by khainguyen95** [getsentry/docker-sentry#124]
Hello,
I will be so grateful if someone can help me with this issue.
I get this error :
```Sun Jan 28 13:55:30 2018 - *** uWSGI listen queue of socket “0.0.0.0:9000” (fd: 3) full !!! (101/100) ***
Sun Jan 28 13:55:31 2018 - *** uWSGI listen queue of socket “0.0.0.0:9000” (fd: 3) full !!! (101/100) ***
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
goodbye to uWSGI.
```
Thanks so much!

**Comment by R4ein** [comment]
Hello,

Getting the same issue here:

```
Thu Feb 22 09:57:16 2018 - *** uWSGI listen queue of socket "0.0.0.0:9000" (fd: 3) full !!! (101/100) ***
Thu Feb 22 09:57:18 2018 - *** uWSGI listen queue of socket "0.0.0.0:9000" (fd: 3) full !!! (100/100) ***
```

Managed to tune some limits and get some resources for sentry, also updated livenessProbe with a bigger timeout, and it still dies from time to time. Any ideas on how to deal with this? Do I have to scale up web worker?

**Comment by mattrobenolt** [comment]
This is absolutely a capacity issue. You can run more concurrent workers with `-c 24` or whatever to match how many CPUs you have/want to use. Or you may need to expand into multiple containers across more than one machine. This error is just saying “I can’t do anymore, but you’re giving me more to do.”
