### ISSUE TITLE
KeyError  u'REQUEST_METHOD'

### ISSUE THREAD

**Issue by iotexsystems** [getsentry/docker-sentry#132]
Hello,

I just installed doker-sentry a few days ago. Today I got this weird error. The IP-Adress belongs to some shady websniffing site. I am actually worried about the security of the system.
Can anyone tell me whats goind on here?

```
KeyError: u'REQUEST_METHOD'
  File "raven/middleware.py", line 98, in __call__
    iterable = self.application(environ, start_response)
  File "sentry/wsgi.py", line 41, in __call__
    response = super(FileWrapperWSGIHandler, self).__call__(environ, start_response)
  File "django/core/handlers/wsgi.py", line 196, in __call__
    request = self.request_class(environ)
  File "django/core/handlers/wsgi.py", line 91, in __init__
    self.method = environ['REQUEST_METHOD'].upper()
```
```

query | SELECT "django_site"."id", "django_site"."domain", "django_site"."name" FROM "django_site" WHERE "django_site"."id" = 1
-- | --
```

```
REMOTE_ADDR | 45.79.187.249
-- | --
SERVER_NAME | 12011a329fc7
SERVER_PORT | 9000

```

Thanks for any help! :)

Lukas

**Comment by mattrobenolt** [comment]
Do you run nginx or anything in front? If not, you absolutely should. My guess is somehow they constructed some malformed HTTP request. A real web server would reject it or at least would guarantee the request passed back was correctly formatted.

**Comment by iotexsystems** [comment]
Just in case anybody else is having a similiar issue: blocking ports in ufw does not work for docker containers. You have to change bindings in the config, so nobody can access directly without nginx in front.
