### ISSUE TITLE
Build using build-git.sh fails

### ISSUE THREAD

**Issue by carukc** [getsentry/docker-sentry#133]
Hello,

I'm trying to build using build-git.sh but get the following errors:

`command failed [yarn --version] via [/usr/src/sentry]
using node (v4.6.0) and npm (2.15.9)
npm WARN deprecated babel-preset-latest@6.24.1: We're super 😸  excited that you're trying to use ES2017+ syntax, but instead of making more yearly presets 😭 , Babel now has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. preset-env without options will compile ES2015+ down to ES5 just like using all the presets together and thus is more future proof. It also allows you to target specific browsers so that Babel can do less work and you can ship native ES2015+ to user 😎 ! We are also in the process of releasing v7, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and help test it out in beta! Thanks so much for using Babel 🙏, please give us a follow on Twitter @babeljs for news on Babel, join slack.babeljs.io for discussion/development and help support the project at opencollective.com/babel
npm WARN engine compression-webpack-plugin@1.1.11: wanted: {"node":">= 4.8 < 5.0.0 || >= 5.10"} (current: {"node":"4.6.0","npm":"2.15.9"})
npm WARN engine less-loader@4.1.0: wanted: {"node":">= 4.8 < 5.0.0 || >= 5.10"} (current: {"node":"4.6.0","npm":"2.15.9"})
npm WARN engine react-hot-loader@3.1.3: wanted: {"node":">= 6"} (current: {"node":"4.6.0","npm":"2.15.9"})
npm WARN engine extract-text-webpack-plugin@3.0.2: wanted: {"node":">= 4.8 < 5.0.0 || >= 5.10"} (current: {"node":"4.6.0","npm":"2.15.9"})
npm WARN engine svg-sprite-loader@3.8.0: wanted: {"node":">=6"} (current: {"node":"4.6.0","npm":"2.15.9"})
npm WARN optional dep failed, continuing fsevents@1.2.4
npm WARN peerDependencies The peer dependency react@^15.4.2 included from react-addons-css-transition-group will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency emotion@8 included from grid-emotion will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react-emotion@8 included from grid-emotion will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency enzyme@^3.0.0 included from enzyme-adapter-react-16 will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated babel-preset-es2017@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated babel-preset-es2016@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN peerDependencies The peer dependency enzyme@^3.0.0 included from enzyme-to-json will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react@>=0.13.0 <16 included from reflux will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN engine schema-utils@0.4.5: wanted: {"node":">= 4.8.0 || >= 6.9.0 || >= 8.9.0"} (current: {"node":"4.6.0","npm":"2.15.9"})
npm WARN deprecated nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN engine punycode@2.1.1: wanted: {"node":">=6"} (current: {"node":"4.6.0","npm":"2.15.9"})
npm WARN engine punycode@2.1.1: wanted: {"node":">=6"} (current: {"node":"4.6.0","npm":"2.15.9"})
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! install trying to install 3.3.0 to /usr/src/sentry/node_modules/enzyme
npm ERR! install but already installed versions [ '3.3.0' ]
npm ERR! install trying to install 1.1.3 to /usr/src/sentry/node_modules/enzyme/node_modules/is-callable
npm ERR! install but already installed versions [ '1.1.3' ]
npm ERR! install trying to install 1.0.1 to /usr/src/sentry/node_modules/enzyme/node_modules/has
npm ERR! install but already installed versions [ '1.0.1' ]
npm ERR! install trying to install 1.0.0 to /usr/src/sentry/node_modules/enzyme/node_modules/is-boolean-object
npm ERR! install but already installed versions [ '1.0.0' ]
npm ERR! install trying to install 0.1.1 to /usr/src/sentry/node_modules/enzyme/node_modules/is-subset
npm ERR! install but already installed versions [ '0.1.1' ]
npm ERR! install trying to install 1.0.4 to /usr/src/sentry/node_modules/enzyme/node_modules/is-string
npm ERR! install but already installed versions [ '1.0.4' ]
npm ERR! install trying to install 1.0.3 to /usr/src/sentry/node_modules/enzyme/node_modules/is-number-object
npm ERR! install but already installed versions [ '1.0.3' ]
npm ERR! install trying to install 1.0.1 to /usr/src/sentry/node_modules/enzyme/node_modules/object-is
npm ERR! install but already installed versions [ '1.0.1' ]
npm ERR! install trying to install 1.0.4 to /usr/src/sentry/node_modules/enzyme/node_modules/object.values
npm ERR! install but already installed versions [ '1.0.4' ]
npm ERR! install trying to install 2.2.3 to /usr/src/sentry/node_modules/enzyme/node_modules/rst-selector-parser
npm ERR! install but already installed versions [ '2.2.3' ]
npm ERR! install trying to install 3.4.0 to /usr/src/sentry/node_modules/enzyme/node_modules/raf
npm ERR! install but already installed versions [ '3.4.0' ]
npm ERR! install trying to install 1.0.4 to /usr/src/sentry/node_modules/enzyme/node_modules/object.entries
npm ERR! install but already installed versions [ '1.0.4' ]
npm ERR! install trying to install 4.1.0 to /usr/src/sentry/node_modules/enzyme/node_modules/object.assign
npm ERR! install but already installed versions [ '4.1.0' ]
npm ERR! install trying to install 1.0.0-rc.2 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio
npm ERR! install but already installed versions [ '1.0.0-rc.2' ]
npm ERR! install trying to install 1.6.0 to /usr/src/sentry/node_modules/enzyme/node_modules/object-inspect
npm ERR! install but already installed versions [ '1.6.0' ]
npm ERR! install trying to install 1.1.0 to /usr/src/sentry/node_modules/enzyme/node_modules/function.prototype.name
npm ERR! install but already installed versions [ '1.1.0' ]
npm ERR! install trying to install 2.1.0 to /usr/src/sentry/node_modules/enzyme/node_modules/raf/node_modules/performance-now
npm ERR! install but already installed versions [ '2.1.0' ]
npm ERR! install trying to install 1.1.1 to /usr/src/sentry/node_modules/enzyme/node_modules/has/node_modules/function-bind
npm ERR! install but already installed versions [ '1.1.1' ]
npm ERR! install trying to install 1.1.1 to /usr/src/sentry/node_modules/enzyme/node_modules/function.prototype.name/node_modules/function-bind
npm ERR! install but already installed versions [ '1.1.1' ]
npm ERR! install trying to install 1.1.2 to /usr/src/sentry/node_modules/enzyme/node_modules/function.prototype.name/node_modules/define-properties
npm ERR! install but already installed versions [ '1.1.2' ]
npm ERR! install trying to install 1.1.1 to /usr/src/sentry/node_modules/enzyme/node_modules/object.values/node_modules/function-bind
npm ERR! install but already installed versions [ '1.1.1' ]
npm ERR! install trying to install 1.1.2 to /usr/src/sentry/node_modules/enzyme/node_modules/object.values/node_modules/define-properties
npm ERR! install but already installed versions [ '1.1.2' ]
npm ERR! install trying to install 1.12.0 to /usr/src/sentry/node_modules/enzyme/node_modules/object.values/node_modules/es-abstract
npm ERR! install but already installed versions [ '1.12.0' ]
npm ERR! install trying to install 1.1.1 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/entities
npm ERR! install but already installed versions [ '1.1.1' ]
npm ERR! install trying to install 3.9.2 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/htmlparser2
npm ERR! install but already installed versions [ '3.9.2' ]
npm ERR! install trying to install 3.0.3 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/parse5
npm ERR! install but already installed versions [ '3.0.3' ]
npm ERR! install trying to install 1.2.0 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/css-select
npm ERR! install but already installed versions [ '1.2.0' ]
npm ERR! install trying to install 0.1.0 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/dom-serializer
npm ERR! install but already installed versions [ '0.1.0' ]
npm ERR! install trying to install 1.1.2 to /usr/src/sentry/node_modules/enzyme/node_modules/object.assign/node_modules/define-properties
npm ERR! install but already installed versions [ '1.1.2' ]
npm ERR! install trying to install 1.0.0 to /usr/src/sentry/node_modules/enzyme/node_modules/object.assign/node_modules/has-symbols
npm ERR! install but already installed versions [ '1.0.0' ]
npm ERR! install trying to install 1.1.1 to /usr/src/sentry/node_modules/enzyme/node_modules/object.assign/node_modules/function-bind
npm ERR! install but already installed versions [ '1.1.1' ]
npm ERR! install trying to install 1.0.11 to /usr/src/sentry/node_modules/enzyme/node_modules/object.assign/node_modules/object-keys
npm ERR! install but already installed versions [ '1.0.11' ]
npm ERR! install trying to install 1.1.2 to /usr/src/sentry/node_modules/enzyme/node_modules/object.entries/node_modules/define-properties
npm ERR! install but already installed versions [ '1.1.2' ]
npm ERR! install trying to install 1.12.0 to /usr/src/sentry/node_modules/enzyme/node_modules/object.entries/node_modules/es-abstract
npm ERR! install but already installed versions [ '1.12.0' ]
npm ERR! install trying to install 1.1.1 to /usr/src/sentry/node_modules/enzyme/node_modules/object.entries/node_modules/function-bind
npm ERR! install but already installed versions [ '1.1.1' ]
npm ERR! install trying to install 1.1.3 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/dom-serializer/node_modules/domelementtype
npm ERR! install but already installed versions [ '1.1.3' ]
npm ERR! install trying to install 1.0.11 to /usr/src/sentry/node_modules/enzyme/node_modules/function.prototype.name/node_modules/define-properties/node_modules/object-keys
npm ERR! install but already installed versions [ '1.0.11' ]
npm ERR! install trying to install 2.0.5 to /usr/src/sentry/node_modules/enzyme/node_modules/function.prototype.name/node_modules/define-properties/node_modules/foreach
npm ERR! install but already installed versions [ '2.0.5' ]
npm ERR! install trying to install 2.0.5 to /usr/src/sentry/node_modules/enzyme/node_modules/object.values/node_modules/define-properties/node_modules/foreach
npm ERR! install but already installed versions [ '2.0.5' ]
npm ERR! install trying to install 1.0.11 to /usr/src/sentry/node_modules/enzyme/node_modules/object.values/node_modules/define-properties/node_modules/object-keys
npm ERR! install but already installed versions [ '1.0.11' ]
npm ERR! install trying to install 2.0.5 to /usr/src/sentry/node_modules/enzyme/node_modules/object.assign/node_modules/define-properties/node_modules/foreach
npm ERR! install but already installed versions [ '2.0.5' ]
npm ERR! install trying to install 1.0.0 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/css-select/node_modules/boolbase
npm ERR! install but already installed versions [ '1.0.0' ]
npm ERR! install trying to install 2.1.0 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/css-select/node_modules/css-what
npm ERR! install but already installed versions [ '2.1.0' ]
npm ERR! install trying to install 1.0.1 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/css-select/node_modules/nth-check
npm ERR! install but already installed versions [ '1.0.1' ]
npm ERR! install trying to install 1.5.1 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/css-select/node_modules/domutils
npm ERR! install but already installed versions [ '1.5.1' ]
npm ERR! install trying to install 1.3.0 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/htmlparser2/node_modules/domelementtype
npm ERR! install but already installed versions [ '1.3.0' ]
npm ERR! install trying to install 1.7.0 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/htmlparser2/node_modules/domutils
npm ERR! install but already installed versions [ '1.7.0' ]
npm ERR! install trying to install 2.3.6 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/htmlparser2/node_modules/readable-stream
npm ERR! install but already installed versions [ '2.3.6' ]
npm ERR! install trying to install 2.0.3 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/htmlparser2/node_modules/inherits
npm ERR! install but already installed versions [ '2.0.3' ]
npm ERR! install trying to install 2.4.2 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/htmlparser2/node_modules/domhandler
npm ERR! install but already installed versions [ '2.4.2' ]
npm ERR! install trying to install 2.0.5 to /usr/src/sentry/node_modules/enzyme/node_modules/object.entries/node_modules/define-properties/node_modules/foreach
npm ERR! install but already installed versions [ '2.0.5' ]
npm ERR! install trying to install 1.0.11 to /usr/src/sentry/node_modules/enzyme/node_modules/object.entries/node_modules/define-properties/node_modules/object-keys
npm ERR! install but already installed versions [ '1.0.11' ]
npm ERR! install trying to install 4.4.0 to /usr/src/sentry/node_modules/enzyme/node_modules/rst-selector-parser/node_modules/lodash.flattendeep
npm ERR! install but already installed versions [ '4.4.0' ]
npm ERR! install trying to install 2.13.0 to /usr/src/sentry/node_modules/enzyme/node_modules/rst-selector-parser/node_modules/nearley
npm ERR! install but already installed versions [ '2.13.0' ]
npm ERR! install trying to install 1.3.0 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/css-select/node_modules/domutils/node_modules/domelementtype
npm ERR! install but already installed versions [ '1.3.0' ]
npm ERR! install trying to install 10.3.0 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/parse5/node_modules/@types/node
npm ERR! install but already installed versions [ '10.3.0' ]
npm ERR! install trying to install 1.0.4 to /usr/src/sentry/node_modules/enzyme/node_modules/object.values/node_modules/es-abstract/node_modules/is-regex
npm ERR! install but already installed versions [ '1.0.4' ]
npm ERR! install trying to install 1.1.1 to /usr/src/sentry/node_modules/enzyme/node_modules/object.values/node_modules/es-abstract/node_modules/es-to-primitive
npm ERR! install but already installed versions [ '1.1.1' ]
npm ERR! install trying to install 1.1.1 to /usr/src/sentry/node_modules/enzyme/node_modules/object.entries/node_modules/es-abstract/node_modules/es-to-primitive
npm ERR! install but already installed versions [ '1.1.1' ]
npm ERR! install trying to install 1.0.4 to /usr/src/sentry/node_modules/enzyme/node_modules/object.entries/node_modules/es-abstract/node_modules/is-regex
npm ERR! install but already installed versions [ '1.0.4' ]
npm ERR! install trying to install 5.5.0 to /usr/src/sentry/node_modules/enzyme/node_modules/rst-selector-parser/node_modules/nearley/node_modules/semver
npm ERR! install but already installed versions [ '5.5.0' ]
npm ERR! install trying to install 0.4.6 to /usr/src/sentry/node_modules/enzyme/node_modules/rst-selector-parser/node_modules/nearley/node_modules/randexp
npm ERR! install but already installed versions [ '0.4.6' ]
npm ERR! install trying to install 1.0.0 to /usr/src/sentry/node_modules/enzyme/node_modules/rst-selector-parser/node_modules/nearley/node_modules/railroad-diagrams
npm ERR! install but already installed versions [ '1.0.0' ]
npm ERR! install trying to install 1.6.2 to /usr/src/sentry/node_modules/enzyme/node_modules/rst-selector-parser/node_modules/nearley/node_modules/nomnom
npm ERR! install but already installed versions [ '1.6.2' ]
npm ERR! install trying to install 5.1.2 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/htmlparser2/node_modules/readable-stream/node_modules/safe-buffer
npm ERR! install but already installed versions [ '5.1.2' ]
npm ERR! install trying to install 1.0.2 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/htmlparser2/node_modules/readable-stream/node_modules/core-util-is
npm ERR! install but already installed versions [ '1.0.2' ]
npm ERR! install trying to install 1.0.2 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/htmlparser2/node_modules/readable-stream/node_modules/util-deprecate
npm ERR! install but already installed versions [ '1.0.2' ]
npm ERR! install trying to install 1.1.1 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/htmlparser2/node_modules/readable-stream/node_modules/string_decoder
npm ERR! install but already installed versions [ '1.1.1' ]
npm ERR! install trying to install 1.0.0 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/htmlparser2/node_modules/readable-stream/node_modules/isarray
npm ERR! install but already installed versions [ '1.0.0' ]
npm ERR! install trying to install 2.0.0 to /usr/src/sentry/node_modules/enzyme/node_modules/cheerio/node_modules/htmlparser2/node_modules/readable-stream/node_modules/process-nextick-args
npm ERR! install but already installed versions [ '2.0.0' ]
npm ERR! install trying to install 0.1.15 to /usr/src/sentry/node_modules/enzyme/node_modules/rst-selector-parser/node_modules/nearley/node_modules/randexp/node_modules/ret
npm ERR! install but already installed versions [ '0.1.15' ]
npm ERR! install trying to install 1.0.0 to /usr/src/sentry/node_modules/enzyme/node_modules/rst-selector-parser/node_modules/nearley/node_modules/randexp/node_modules/discontinuous-range
npm ERR! install but already installed versions [ '1.0.0' ]
npm ERR! install trying to install 1.0.1 to /usr/src/sentry/node_modules/enzyme/node_modules/object.entries/node_modules/es-abstract/node_modules/es-to-primitive/node_modules/is-symbol
npm ERR! install but already installed versions [ '1.0.1' ]
npm ERR! install trying to install 1.0.1 to /usr/src/sentry/node_modules/enzyme/node_modules/object.entries/node_modules/es-abstract/node_modules/es-to-primitive/node_modules/is-date-object
npm ERR! install but already installed versions [ '1.0.1' ]
npm ERR! install trying to install 1.0.1 to /usr/src/sentry/node_modules/enzyme/node_modules/object.values/node_modules/es-abstract/node_modules/es-to-primitive/node_modules/is-symbol
npm ERR! install but already installed versions [ '1.0.1' ]
npm ERR! install trying to install 1.0.1 to /usr/src/sentry/node_modules/enzyme/node_modules/object.values/node_modules/es-abstract/node_modules/es-to-primitive/node_modules/is-date-object
npm ERR! install but already installed versions [ '1.0.1' ]
npm ERR! install trying to install 1.4.4 to /usr/src/sentry/node_modules/enzyme/node_modules/rst-selector-parser/node_modules/nearley/node_modules/nomnom/node_modules/underscore
npm ERR! install but already installed versions [ '1.4.4' ]
npm ERR! install trying to install 0.5.1 to /usr/src/sentry/node_modules/enzyme/node_modules/rst-selector-parser/node_modules/nearley/node_modules/nomnom/node_modules/colors
npm ERR! install but already installed versions [ '0.5.1' ]
npm ERR! Linux 4.13.0-43-generic
npm ERR! argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "install" "--production" "--quiet"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package emotion@9.1.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grid-emotion@2.1.0 wants emotion@8
npm ERR! peerinvalid Peer react-emotion@9.1.2 wants emotion@^9.1.2

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/sentry/npm-debug.log
command failed [npm install --production --quiet] via [/usr/src/sentry]
Traceback (most recent call last):
  File "setup.py", line 154, in <module>
    'Topic :: Software Development'
  File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 204, in run
    self.run_command('build')
  File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 97, in run
    self.run_command('build_integration_docs')
  File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/src/sentry/src/sentry/utils/distutils/commands/base.py", line 186, in run
    self._setup_npm()
  File "/usr/src/sentry/src/sentry/utils/distutils/commands/base.py", line 145, in _setup_npm
    self._run_command(['npm', 'install', '--production', '--quiet'])
  File "/usr/src/sentry/src/sentry/utils/distutils/commands/base.py", line 150, in _run_command
    return check_output(cmd, cwd=self.work_path, env=env)
  File "/usr/local/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['npm', 'install', '--production', '--quiet']' returned non-zero exit status 1
The command '/bin/sh -c [ "$SENTRY_BUILD" != '' ]     && export NODE_VERSION=4.6.0     && export GNUPGHOME="$(mktemp -d)"     && for key in       9554F04D7259F04124DE6B476D5A82AC7E37093B       94AE36675C464D64BAFA68DD7434390BDBE9B9C5       0034A06D9D9B0064CE8ADF6BF1747F4AD2306D93       FD3A5288F042B6850C66B31F09FE44734EB7990E       71DCFD284A79C3B38668286BC97EC7A07EDE3FC1       DD8F2338BAE7501E3DD5AC78C273792F7D83545D       B9AE9905FFD7803F25714661B63B535A4C206CA9       C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8     ; do       gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key";     done     && mkdir -p /usr/local/node && PATH=/usr/local/node/bin:$PATH     && apt-get update && apt-get install -y --no-install-recommends make g++ wget     && rm -rf /var/lib/apt/lists/*     && wget "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz"     && wget "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc"     && gpg --verify SHASUMS256.txt.asc     && grep " node-v$NODE_VERSION-linux-x64.tar.gz\$" SHASUMS256.txt.asc | sha256sum -c -     && tar -xzf "node-v$NODE_VERSION-linux-x64.tar.gz" -C /usr/local/node --strip-components=1     && rm -r "$GNUPGHOME" "node-v$NODE_VERSION-linux-x64.tar.gz" SHASUMS256.txt.asc     && mkdir -p /usr/src/sentry     && cd /usr/src/sentry     && wget -qO - "https://github.com/getsentry/sentry/archive/${SENTRY_BUILD}.tar.gz" | tar -xzf - --strip-components=1     && python setup.py bdist_wheel     && npm cache clear     && rm -rf /usr/local/node     && pip install dist/*.whl     && apt-get purge -y --auto-remove make g++ wget     && rm -rf /usr/src/sentry' returned a non-zero code: 1
`

I will try to retrieve the npm-debug.log file as indicated.

I'll also compare the Dockerfile.dev in the main repo with the with the one in the 8.22 directory of docker-sentry.

Chris

**Comment by mattrobenolt** [comment]
This `git` build version is a bit outdated at the moment and won't work. I'll try to get it updated when we start tagging for Sentry 9.

**Comment by carukc** [comment]
Thank you!
