### ISSUE TITLE
Suggest: add "official" Sentry docker-compose.yml example

### ISSUE THREAD

**Issue by harobed** [getsentry/docker-sentry#135]
Hi,

Every time I lose a lot of time to find an updated and working Sentry `docker-compose.yml` file.

I suggest to add "official" Sentry docker-compose.yml example like [Running Sentry in Docker Compose](https://medium.com/@prasincs/running-sentry-in-docker-compose-63b1c2683493) in this repository.

Best regards,
Stéphane

**Comment by denyo** [comment]
I think there is one here: https://github.com/getsentry/onpremise
Although maybe outdated.

**Comment by harobed** [comment]
> I think there is one here: https://github.com/getsentry/onpremise
> Although maybe outdated.

Thanks.

Maybe add link to this repository in [getsentry/docker-sentry/README.md](https://github.com/getsentry/docker-sentry/blob/master/README.md)?
