### ISSUE TITLE
sentry not update the count when filter issues

### ISSUE THREAD

**Issue by erayozcan** [getsentry/docker-sentry#137]
Hi,

In sentry Issues page, when I filter the issues, the total issue count per issue not updated. For example there is 1k for one issue, I filtered that using tag, 10 record listed but the count on top the page still show 1k. Are the any way for updating the count according to the filter?

Thx.

**Comment by mattrobenolt** [comment]
This is a major technical issue that is being addressed with lots of work at the moment. So there's nothing really actionable here, especially in this repository.
