### ISSUE TITLE
ARM64 support 

### ISSUE THREAD

**Issue by odidev** [getsentry/docker-sentry#138]
It looks like Sentry doesn't support **ARM64** support.

While building Sentry package I have found issues for following packages:
```
Symbolic
Semaphore
```

For this, I have compiled and prepared ```whl``` files for failure packages.

Using these I can build and use ```Sentry``` package very well.
The whl files are:
```
symbolic-5.0.2-py2.py3-none-linux_aarch64.whl
semaphore-0.1.1-py2.py3-none-linux_aarch64.whl
```

I would be happy to upload modified ```whl``` files, given that **PR** of this nature would be accepted.

**Comment by odidev** [comment]
@lag-linaro : Thanks, I will let you know if any support is required. :)

**Comment by lag-linaro** [comment]
@odidev as an aside, I mailed you -- did you get it?

**Comment by odidev** [comment]
Raised PR at #139 with required changes to support both amd64 and arm64v8 architectures.

**Comment by lag-linaro** [comment]
@odidev, looks like the Travis tests failed.

https://travis-ci.org/getsentry/docker-sentry/jobs/404764977

Would you be able to take a look?

**Comment by mattrobenolt** [comment]
See 
https://github.com/getsentry/docker-sentry/pull/139#issuecomment-405861462

**Comment by mattrobenolt** [comment]
That’s not true. It fails due to gpg not even being installed since the base image is changed from Jessie to Stretch as well. More work need to be done before we can even go to Stretch.

**Comment by odidev** [comment]
@mattrobenolt : is there any way that we can support sentry for ARM64?
