### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by szepeviktor** [getsentry/docker-sentry#145]
Hello!

When I told our server `docker pull sentry:9.0-onbuild` it updated the container.

> Digest: sha256:08fd61439a44562f81fb3eaaa6c489a798c58d1961dcde0db03406141bb32539
> Status: Downloaded newer image for sentry:9.0-onbuild

Could you please point out where do I find the changes?

*We run sentry for a couple of weeks*

**Comment by szepeviktor** [comment]
@mattrobenolt Thank you.
sentry's tag: https://github.com/getsentry/sentry/tree/9.0.0 was on 25th on June. Could it be that the sentry:9.0-onbuild has changed meanwhile?
I am interested in the changes of the container.

**Comment by mattrobenolt** [comment]
If I had to guess, one of the base images that it's built on top of was updated. This is a sanctioned, official docker image, so they get rebuilt periodically for security updates and whatnot to the underlying base images.

**Comment by szepeviktor** [comment]
Thanks again.
So you do not publish **different** containers as `sentry:9.0-onbuild`?

**Comment by mattrobenolt** [comment]
No. I don't actually publish or push any. I submit a PR with metadata to their repository, and they have bots that build and publish into their repositories.

See https://github.com/docker-library/official-images/blob/master/library/sentry

**Comment by szepeviktor** [comment]
Now I see how the change introduces.
Thank you for pointing out all these.

All the best!

**Comment by tianon** [comment]
Just for reference (it's also linked from https://hub.docker.com/_/sentry/), you can get a lot of useful information from https://github.com/docker-library/repo-info -- for example, see https://github.com/docker-library/repo-info/commit/0caeae8c28fd127a018fceeb49f400820521a112#diff-43f4f55a3e01a275932e76ea419097e0 for some details on the most recent push to `sentry:9.0-onbuild`.
