### ISSUE TITLE
google.cloud.storage.client missing

### ISSUE THREAD

**Issue by daniel5gh** [getsentry/docker-sentry#148]
Hi,

I am running into an issue while using the 9.0 version of the image.

After setting up the `gcs` filestore backend, and at the time of uploading a file, I get to see the following error:
```
ImproperlyConfigured: Error importing module sentry.filestore.gcs: "No module named google.cloud.storage.client"
```

After running the following inside the running container and trying again it is resolved:
```bash
pip install google-cloud-storage
kill -HUP 1
```

I am unable to test this in a non docker configuration so I am unsure if this is also an issue with sentry when installed via pip directly for example. I did notice the `Dockerfile` installs the sentry wheel, so it looks like the dependencies of that wheel are not complete.

Thanks

**Comment by mattrobenolt** [comment]
This is listed as an option dependency which we don't install into the container by default at this time. I'd just suggest using the `onbuild` tags and adding it into your own `requirements.txt` to get it installed.

We will likely include these optional dependencies in the future.

**Comment by daniel5gh** [comment]
thanks for the swift response!
