### ISSUE TITLE
Docker Healthcheck

### ISSUE THREAD

**Issue by mscansian** [getsentry/docker-sentry#149]
Is there a reason for not using the [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck) instruction? It should be fairly easy since wget is already being installed and it helps in some cases where the server gets stuck when receiving too many requests concurrently.

Thinking about something straightforward as:
`HEALTHCHECK wget --quiet --tries=1 --spider http://localhost:9000 || exit 1`

**Comment by tianon** [comment]
https://github.com/docker-library/faq#healthcheck is relevant and might be useful

**Comment by mscansian** [comment]
Makes sense. Thanks :)
