### ISSUE TITLE
Runing sentry UI

### ISSUE THREAD

**Issue by john1452** [getsentry/docker-sentry#150]
Hi there, 

I have successfully installed sentry on my local host docker. But wondering how I can access the web client?
I tried looking at the urls for install application via docker ps command and following is what i got.

![image](https://user-images.githubusercontent.com/30621184/47625064-813b1180-db87-11e8-961e-590880666563.png)

**Comment by markstory** [comment]
You should try http://<dockerhost>:9000

**Comment by niklasbeinghaus** [comment]
You need to use a port mapping on the my-sentry container. If you missed doing this, add it by stopping and removing the container:
"""
docker stop my-sentry && docker rm my-sentry
"""

then, add a port-mapping by starting the container like this:
"""
docker run -d --name my-sentry -e SENTRY_SECRET_KEY='' -p 8080:9000 --link sentry-redis:redis --link sentry-postgres:postgres sentry
"""
