### ISSUE TITLE
How to build image sentry:9.0 from source code.

### ISSUE THREAD

**Issue by kkdev163** [getsentry/docker-sentry#158]
As the [Dockerfile](https://github.com/getsentry/docker-sentry/blob/master/9.0/Dockerfile) shows sentry:9.0 was build from .whl files. If I want to build sentry:9.0 from the source code, is there any doc can helps me. I have been find Dockerfile.dev from this [repo](https://github.com/getsentry/sentry), but it tell us this should not  be used in production! I'm really Newbie to python and docker. Can someone give me some doc or learning path to achieve this goal.

**Comment by mattrobenolt** [comment]
I'm not sure what your intention is, but the `git` based images here build from source.
