### ISSUE TITLE
"sentry:git-onbuild" image not found in Docker hub

### ISSUE THREAD

**Issue by bqbn** [getsentry/docker-sentry#159]
This repo contains an onbuild Dockerfile for building Sentry master branch, i.e.: 

* https://github.com/getsentry/docker-sentry/tree/master/git/onbuild

however, when I tried to build an image based on that, the error says

```
$ docker pull sentry:git-onbuild
Error response from daemon: manifest for sentry:git-onbuild not found
```

What is the onbuild tag I can use to build a custom image for Sentry master branch? Or do I need to copy https://github.com/getsentry/docker-sentry/blob/master/git/Dockerfile then build it myself? The concern about copying that Dockerfile is that it can be out of sync with the repo.

**Comment by mattrobenolt** [comment]
We don't push this because it's intended to be built from a git sha when you want it, we don't publish every sha to DockerHub. The included [build-git.sh](https://github.com/getsentry/docker-sentry/blob/master/build-git.sh) script should be enough for you.
