### ISSUE TITLE
Remove tini

### ISSUE THREAD

**Issue by rgarrigue** [getsentry/docker-sentry#160]
Hi

Tini's now shipped with docker, available through a `--init` option on docker cli or `init: true` field in compose file, see https://docs.docker.com/compose/compose-file/#init.

Might want to remove it ?

**Comment by mattrobenolt** [comment]
I think it's not a fair assumption that everyone will always be passing `--init` or `init: true` and by removing this, then potentially breaks for everyone else.

A better question is, is there a way to detect this from within the container, and just not run tini?

**Comment by BYK** [comment]
I've done some research and wasn't able to find a satisfactory solution. We may add the `--init` parameter to the docs and ask people to use Docker 1.13+ which sounds reasonable as it is pretty old.

Any ideas @rgarrigue, @mattrobenolt?

**Comment by rgarrigue** [comment]
@mattrobenolt arguments are LGTM.
On the contrary, you could argue KISS, adding a init system should be up to the user, and users not whiling this be able to use the official image without the overhead. 
But sentry's not exactly the product you want to run tons of instances, so talking about overhead is nit picking. I'ld prefer arguing about adding something like gozu to step down from root.

So well, your product, your call. My original issue was just information about a possibility.

To answer about tini detection, here's an example, there a re many way, I don't know which one got the  longest beard.

```
➜ docker run --init debian:9 cat /proc/1/comm 
init
➜ docker run debian:9 cat /proc/1/comm    
cat
```

**Comment by yosifkit** [comment]
Part of @tianon's [comment from official-images/issues#5002](https://github.com/docker-library/official-images/issues/5002#issuecomment-434113640) is related:

>unfortunately for image authors, there's no `Dockerfile` instruction to tell Docker that it should do this, so image authors who want their images to work out of the box without `--init` and know that the software they're containing isn't well-behaved in this regard have to embed one of the listed solutions themselves, hence our explicit `tini` recommendation

So, while you could just use documentation to tell users to use `--init`, they probably won't and then will complain if the image has a zombie problem.

I applaud the effort to detect that the entrypoint is running under `--init`, though I can't remember if there is harm in `tini tini entrypoint.sh ...`.  On a related note, a simple `[ "$$" = 1 ]` can detect if `tini` is needed (i.e. are we pid 1). :smile:

**Comment by mattrobenolt** [comment]
A good popular example of a place where we still need it is for deployments in Kubernetes. There's no way to indicate the `--init` flag, and as @yosifkit mentioned, even if it were a thing that could be configured, people won't unless it was the default behavior.
