### ISSUE TITLE
registration email missing domain

### ISSUE THREAD

**Issue by benjamin-bergia** [getsentry/docker-sentry#187]
Hi,

when sending registration email, the link received in the email contains only the path ie `/accept/*****`. I am running the official sentry:9 image.
Here is the env vars that are set:
```
SENTRY_DB_NAME
SENTRY_REDIS_HOST
SENTRY_REDIS_PORT
SENTRY_REDIS_DB
SENTRY_FILESTORE_DIR
SENTRY_SERVER_EMAIL
SENTRY_EMAIL_HOST
SENTRY_EMAIL_PORT
SENTRY_SECRET_KEY
SENTRY_DB_USER
SENTRY_DB_PASSWORD
```

**Comment by benjamin-bergia** [comment]
I added a system.url-prefix in config.yml and it seems to solve this. Is there any way to set system.url-prefix in the sentry.conf.py file instead, where I can read from the environment?

**Comment by mattrobenolt** [comment]
Yeah, you can set it as a key in SENTRY_OPTIONS. 

So something like:

```python
SENTRY_OPTIONS['system.url-prefix'] = os.environ['whatever you want']
```

**Comment by benjamin-bergia** [comment]
Nice, thank you.
