### ISSUE TITLE
Take over ownership

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/docker-sentry#19]
How do we (Sentry) become owners of this repository on Docker Hub?

I was going to start publishing to a `getsentry/sentry`, but realized, it'd probably be better if we owned this instead and controlled our own releases, etc.

I was going to be publishing a new repository at https://github.com/getsentry/docker-sentry. Would we be able to point that one to the official registry? Or would it be developed in here?

Thanks.

**Comment by tianon** [comment]
That would be absolutely fantastic! :tada:

There's a little bit of info about the process we prefer over at https://github.com/docker-library/official-images#maintainership, and so if you're ready to take the torch I can add you as an admin in the https://github.com/docker-library-transitioner organization and move this repo over so you can rename/move it to the getsentry organization, assuming @yosifkit doesn't have any objections. :+1:  (You haven't really been involved in this repo specifically, but you've contributed positively to others we maintain, so I'm personally a big +1! :heart:)

Sound like a good plan?

**Comment by mattrobenolt** [comment]
Let's do it. :)

**Comment by yosifkit** [comment]
LGTM!

**Comment by md5** [comment]
@tianon @yosifkit Did `docker-library` get opted in to GitHub's [Improved Permissions](https://github.com/orgs/improved-permissions) beta yet? If not, it may be worth figuring out if they can add you. It would allow you to do away with this `docker-library-transitioner` thing and just add outside collaborators as admins directly to `docker-library` repos (which would allow them to complete the transfer).

**Comment by tianon** [comment]
Oh interesting -- nope!

**Comment by mattrobenolt** [comment]
Cool, it's transferred over just fine.

What's needed now to get builds in official-library to be coming from this repo now?

**Comment by mattrobenolt** [comment]
thx for the speedy process, btw. <3

**Comment by md5** [comment]
@tianon You might try pinging support@github.com. I think they'll be happy to add `docker-library`, given the nature of the org.

**Comment by md5** [comment]
Sorry for the OT comments, @mattrobenolt :+1:

**Comment by tianon** [comment]
@mattrobenolt :+1:

You'll probably want to familiarize yourself with https://github.com/docker-library/official-images/blob/master/README.md and [`generate-stackbrew-library.sh` within this repo](https://github.com/getsentry/docker-sentry/blob/master/generate-stackbrew-library.sh), which when run should spit out the contents of https://github.com/docker-library/official-images/blob/master/library/sentry (ready for making a PR to update the image itself).

**Comment by mattrobenolt** [comment]
Rad. Lemme do that. :)

**Comment by tianon** [comment]
@mattrobenolt you'll also want to check out https://github.com/docker-library/docs, which is where the documentation for the image lives (and there's a `README.md` there describing that repo's process as well)

**Comment by mattrobenolt** [comment]
@tianon @yosifkit How does this LICENSE work in this repo? Right now it's licensed to `Docker, Inc`, which is odd for us. I assume we can change this to be our own LICENSE?

**Comment by tianon** [comment]
Uhh, hmm.  I'm not a lawyer, but I would imagine that's OK?  My understanding is that right now it's _copyrighted_ by `Docker, Inc` (and actually, it's really copyrighted to the individual contributors unless they explicitly signed-off their copyright), so the name in the license should be safe to change without a problem AFAIU.

**Comment by mattrobenolt** [comment]
/cc @dcramer 

Going to assume it's ok to change the LICENSE here to our 3-clause BSD? Or do you want our Apache?

**Comment by md5** [comment]
@tianon Since the only contributors are you and @yosifkit and you worked on this image as part of Infosiftr under an agreement with Docker, Inc, that probably means it's a work for hire and that Docker, Inc. really does have the copyright. Assuming I understand the situation correctly (IANAL, etc).

**Comment by dcramer** [comment]
I prefer Apache. We cant really change the license but we can amend it.

**Comment by mattrobenolt** [comment]
Thanks guys, I think everything is done here for us?

**Comment by tianon** [comment]
I think so! :+1:
