### ISSUE TITLE
404 Error with event committers

### ISSUE THREAD

**Issue by chuyun** [getsentry/docker-sentry#193]
there is something wrong with it. such as 
![image](https://user-images.githubusercontent.com/19328403/62540150-7dac8780-b889-11e9-8ada-1623d3fd1f3c.png)

**Comment by markstory** [comment]
What makes you think the 404s are a problem? The commiters endpoint uses 404 to signal that no committers could be found.

**Comment by chuyun** [comment]
Thanks, but I think it's unreasonable to use 404 status code to indicate that there is no submitter. In fact, the interface returns okay. Why not put the submitter in the returned data?

**Comment by mattrobenolt** [comment]
This is not exactly a forum to debate our usage of status codes. There’s nothing wrong here and it’s working as intended. 

I personally agree that 404 is kinda weird as opposed to a 200 with say, an empty result instead. But this is definitely the wrong place for this discussion.
