### ISSUE TITLE
Error response from daemon: Cannot restart container 5b40898f7f44: failed to listen to abstract unix socket "/containerd-shim/moby/5b40898f7f442d78153d920f1e457252514114760b7dbd3f23011a2261e81ded/shim.sock": listen unix /containerd-shim/moby/5b40898f7f442d78153d920f1e457252514114760b7dbd3f23011a2261e81ded/shim.sock: bind: address already in use: unknown

### ISSUE THREAD

**Issue by ankitkkumar13** [getsentry/docker-sentry#202]
i have just run the command sudo apt update and after the my sentry ,postgress ,redis and sentry cron is stopped when i trying to restart (because i don't want lost my data and container state) it's give me this error Error response from daemon: Cannot restart container 5b40898f7f44: failed to listen to abstract unix socket "/containerd-shim/moby/5b40898f7f442d78153d920f1e457252514114760b7dbd3f23011a2261e81ded/shim.sock": listen unix /containerd-shim/moby/5b40898f7f442d78153d920f1e457252514114760b7dbd3f23011a2261e81ded/shim.sock: bind: address already in use: unknown

**Comment by Perterually** [comment]
> i have just run the command sudo apt update and after the my sentry ,postgress ,redis and sentry cron is stopped when i trying to restart (because i don't want lost my data and container state) it's give me this error Error response from daemon: Cannot restart container 5b40898f7f44: failed to listen to abstract unix socket "/containerd-shim/moby/5b40898f7f442d78153d920f1e457252514114760b7dbd3f23011a2261e81ded/shim.sock": listen unix /containerd-shim/moby/5b40898f7f442d78153d920f1e457252514114760b7dbd3f23011a2261e81ded/shim.sock: bind: address already in use: unknown
I have the same problem

**Comment by Perterually** [comment]
> i have just run the command sudo apt update and after the my sentry ,postgress ,redis and sentry cron is stopped when i trying to restart (because i don't want lost my data and container state) it's give me this error Error response from daemon: Cannot restart container 5b40898f7f44: failed to listen to abstract unix socket "/containerd-shim/moby/5b40898f7f442d78153d920f1e457252514114760b7dbd3f23011a2261e81ded/shim.sock": listen unix /containerd-shim/moby/5b40898f7f442d78153d920f1e457252514114760b7dbd3f23011a2261e81ded/shim.sock: bind: address already in use: unknown

I have the same problem

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
