### ISSUE TITLE
Get Sentry image running on AWS ECS

### ISSUE THREAD

**Issue by Tontonitch** [getsentry/docker-sentry#206]
Hello

As I don't see any Sentry forum anymore, I ask the question here.
The recommened way to install Sentry is through the deployment of the Docker image.

Due to that, we would like to run this official docker image on AWS ECS (Elastic Container Service). Is this possible? Will it work? Indeed, I don't see any documentation related to that, only some example of use of AWS EC2 to run EC2 instances gathered on the AWS Marketplace.

BR,
Yannick

**Comment by BYK** [comment]
Hi @Tontonitch - not sure why you don't see the forum but it is there and alive at https://forum.sentry.io/. Please create a topic there under the "on-premise" category there :)

Closing the issue.

**Comment by Tontonitch** [comment]
Indeed, now I can see it (at least from home...). I will see tomorrow from work. Thanks Burak
