### ISSUE TITLE
Sentry 10 support

### ISSUE THREAD

**Issue by mznet** [getsentry/docker-sentry#209]
[Sentry 10](https://github.com/getsentry/sentry/releases/tag/10.0.0) has been released few days ago.  It should be dockerized to install easily.

**Comment by BYK** [comment]
That link says: please see our blog post, which has this paragraph in it:

https://blog.sentry.io/2020/01/07/self-hosted-sentry-10-is-ready-to-serve-get-it-while-its-hot
> Long story short, with the help of additional services, Sentry is now a lot more capable. For this reason, we doubled down on our Docker images and Docker Compose based setup.
>
>With this release, the only [supported and recommended way of installing Sentry](https://docs.sentry.io/server/installation/) is through the on-premise repository and via Docker.

**Comment by mznet** [comment]
@BYK I missed that 👍
