### ISSUE TITLE
sentry 10 image not available in docker hub

### ISSUE THREAD

**Issue by LakshmiNarasiman123** [getsentry/docker-sentry#212]
Dear Team,

Sentry 10 is released in github . But we couldnt find it in docker hub ?

Please let us know when it will be released?

**Comment by kamilogorek** [comment]
This repository is no longer maintained. Docker files for Sentry repository live here now: https://github.com/getsentry/sentry/tree/master/docker
It's also up to date on Docker Hub here: https://hub.docker.com/r/getsentry/sentry

**Comment by LakshmiNarasiman123** [comment]
Thanks for the details.

Could you please let me know if you have any steps to upgrade sentry from 9.1.2 to 10.0.0.

Also how to setup sentry using the image https://hub.docker.com/r/getsentry/sentry

**Comment by BYK** [comment]
@LakshmiNarasiman123 please see https://github.com/getsentry/onpremise

It takes care of all the migration steps. You can use the [forums](https://forum.sentry.io) or that repo for questions/issues.

We want to make the image available on the official library and filed issues but the Docker team hasn't been responsive. Feel free to ping them at https://github.com/getsentry/docker-sentry/issues/211 and https://github.com/docker-library/official-images/issues/7831
