### ISSUE TITLE
Provide docs for a proper docker-compose setup to get everything working correctly

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/docker-sentry#23]

**Comment by andrefreitas** [comment]
Take a look at pr #28 :)

**Comment by marksteve** [comment]
Setup is pretty minimal (thanks to the latest changes :D) so I don't think this is needed anymore.

Here's my setup: https://github.com/marksteve/sentry 
I wouldn't mind writing this for every setup I have

**Comment by marksteve** [comment]
Oops. Misread the issue title. Didn't see "docs".

**Comment by mattrobenolt** [comment]
https://github.com/getsentry/onpremise/blob/master/docker-compose.yml
