### ISSUE TITLE
I can't logging into Sentry

### ISSUE THREAD

**Issue by yograterol** [getsentry/docker-sentry#25]
Hi,

I installed Sentry with Docker Compose, but when I try logging into Sentry, Sentry does not do nothing.

**Comment by mattrobenolt** [comment]
What's the error you get? Did you run the syncdb and migrations and createsuperuser?

**Comment by yograterol** [comment]
@mattrobenolt It's work x.x ... But in Celery I found this problem "Error processing 'rule_notify' on 'MailPlugin': [Errno 111] Connection refused"

**Comment by yograterol** [comment]
Ok, I catch the error. When I use haproxy I can't do logging.

**Comment by mattrobenolt** [comment]
> But in Celery I found this problem "Error processing 'rule_notify' on 'MailPlugin': [Errno 111] Connection refused"

To send email, you'll need to configure an external SMTP server, with the `EMAIL_HOST`, etc settings. At least that's what I'm assuming is the cause of the error.

> When I use haproxy I can't do logging.

I'm not sure what this means. Can you clarify?

**Comment by yograterol** [comment]
@mattrobenolt I have Haproxy as frontend of Sentry. 

Haproxy (Port 80) ---> Sentry Port (8080)

When I use this setting, I can't logging.

If just I enter in Sentry (port 8080) works fine.

**Comment by mattrobenolt** [comment]
> When I use this setting, I can't logging.

I'm not sure what you mean by this. Which logging?

Either way, at this point, none of these issues are related to Docker, and you should follow documentation here: https://docs.getsentry.com/on-premise/server/

And if you have issues after following that, can you open an issue on https://github.com/getsentry/sentry ?

Thanks! :)
