### ISSUE TITLE
Update documentation to match reality

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/docker-sentry#27]
Since we've take over, there are a lot of holes in the installation and configuration instructions. These should be updated to match what it's really like to run a Sentry instance.

We'll also want to publish these to docs.getsentry.com as well as docker hub.

- [x] Docker Hub
- [x] docs.getsentry.com

**Comment by marksteve** [comment]
:+1:

**Comment by fiws** [comment]
+1

**Comment by mattrobenolt** [comment]
Docker Hub docs have been updated, but we haven't added docs yet to `docs.getsentry.com`.

**Comment by mattrobenolt** [comment]
See: https://docs.getsentry.com/on-premise/server/installation/docker/
