### ISSUE TITLE
Change SMTP configs

### ISSUE THREAD

**Issue by GSNGamesAlexr** [getsentry/docker-sentry#29]
Hi there. Do we have a way to configure SMTP credentials like SENTRY_SMTP_HOSTNAME etc?
I tried to run sentry-celery container with env variables, like:
docker run ...... -e SENTRY_SMTP_HOSTNAME=smtp_host ...
And nothing.

**Comment by andrefreitas** [comment]
At the moment there is no way of configuring SMTP by environment variables.

This can be easily fixed by changing this file https://github.com/getsentry/docker-sentry/blob/master/docker-links.conf.py

**Comment by mattrobenolt** [comment]
This is solved with 8.0. Release and docs coming soon.
