### ISSUE TITLE
Can't explicitely set EMAIL_USE_TLS to False

### ISSUE THREAD

**Issue by rassie** [getsentry/docker-sentry#37]
Currently, `sentry.conf.py` only checks for existence of `SENTRY_EMAIL_USE_TLS`, so that TLS is on even if the variable is set to False.

**Comment by mattrobenolt** [comment]
Hey @rassie in what case was `SENTRY_EMAIL_USE_TLS` first set, and then you want to change the value?

When I implemented that, I didn't think that'd ever be the case.

**Comment by rassie** [comment]
It's not a sticky setting or something like that, but I'd like my configuration to be explicit in case some default changes someday. So I've seen the `SENTRY_EMAIL_USE_TLS` setting and set it to `False`, which enabled it instead. So to disable TLS, I need to delete this setting, which is just a bit inconvenient. Not a big problem, just consistency and self-documentation for the configuration.

**Comment by mattrobenolt** [comment]
Yeah, the only question is what values are acceptable for booleans from within environment variables? 1/0, y/n, True/False? :)

I'll take care of this, but I want to make sure it's actually intuitive and covers everything expected.

**Comment by MikeVL** [comment]
https://github.com/getsentry/sentry/issues/2653#issuecomment-441220250
