### ISSUE TITLE
Can't change pip's parameters with -onbuild

### ISSUE THREAD

**Issue by rassie** [getsentry/docker-sentry#38]
It's currently not possible to change pip's parameters in any way. One example is using a proxy to download the requirements which requires either a command line option for `pip` or an environment variable, which is impossible to set before `ONBUILD` sets in.

(not sure how to solve this, though)

**Comment by mattrobenolt** [comment]
This is not possible to do with docker. The `ONBUILD` instructions run first and there's no way to interject anything between or before them.

This was a proposal for docker to solve this, but it hasn't gone anywhere afaict: https://github.com/docker/docker/issues/8240

Fortunately, the `onbuild` variant is trivial enough to just copy/paste then change.

You could very easily just copy/paste this into (https://github.com/getsentry/docker-sentry/blob/master/8.0/onbuild/Dockerfile) your own `Dockerfile` and remove the `ONBUILD` instructions. Then you can adjust however you want.
