### ISSUE TITLE
Setting up docker-sentry without --link

### ISSUE THREAD

**Issue by Niler851** [getsentry/docker-sentry#39]
I have a subset of docker avalible at work and i can not use the --link command. 
any ideas on how to get this running without it ?

**Comment by mattrobenolt** [comment]
`--link` is definitely not required. :)

See the docs (https://hub.docker.com/_/sentry/) for all of the Environment Variables.

They're also listed here: https://github.com/getsentry/docker-sentry/blob/master/8.0/sentry.conf.py#L4-L23

And lastly, you can use the `onbuild` variant to just provide your own config file entirely, which is the same as following along here: https://docs.getsentry.com/on-premise/server/installation/
