### ISSUE TITLE
Provide a way to extend the sentry.conf.py instead of overriding it

### ISSUE THREAD

**Issue by rassie** [getsentry/docker-sentry#41]
Currently, one has to either provide a full `sentry.conf.py` or remove it completely. Overriding just a specific setting is not possible, which is a shame, since the default `sentry.conf.py` is neatly done and needn't be copied for every version change.

Context: I needed to override `MESSAGE_STORAGE` and set it to session storage, since our F5 considers the cookie set by the messaging framework broken and blocks the requests.

**Comment by mattrobenolt** [comment]
What would you recommend here? We really want to push users to using the onbuild and providing your own config entirely. This won't scale for very long by doing this.

**Comment by rassie** [comment]
Hmm. I have no idea honestly, I just wish to have a way to override a setting without copying everything, especially since many settings are available through environment variables. Maybe something like `sentry.localconf.py` which would be included at the end of `sentry.conf.py` conditionally?

**Comment by davesave** [comment]
I was looking for the exact thing. on-build is the only solution for changing confs?

By the way, take a look at https://hub.docker.com/r/slafs/sentry/ - VERY configurable via Envs.
- Almost too much :)

**Comment by mattrobenolt** [comment]
There's a reason why we choose not to expose _everything_ as environment variables.

For our case, running Sentry is complex and very often you need the `on-build` variant to make Sentry any bit useful. The base image with environment variables is meant as a jump start, not really a long term and large scale deployment plan.

**Comment by davesave** [comment]
Aight, 
Thanks.

**Comment by mattrobenolt** [comment]
This shouldn't be needed now with https://github.com/getsentry/onpremise
