### ISSUE TITLE
How to set SENTRY_ENABLE_EMAIL_REPLIES to True ?

### ISSUE THREAD

**Issue by LoicMahieu** [getsentry/docker-sentry#55]
I wish use [inbound email via Mailgun](https://docs.getsentry.com/on-premise/server/inbound-mail/). Everything is well configured (I hope) except `SENTRY_ENABLE_EMAIL_REPLIES`.
I tried to set it via environment but obviously config file does not handle it.

**Comment by mattrobenolt** [comment]
I'll add this to the 8.3 packages.

**Comment by mattrobenolt** [comment]
@LoicMahieu Now, as long as you specify the Mandrill API key, `SENTRY_ENABLE_EMAIL_REPLIES` will be enabled implicitly. Or you can pass `SENTRY_ENABLE_EMAIL_REPLIES` explicitly as an env var.

**Comment by LoicMahieu** [comment]
Thanks @mattrobenolt 
Is it will be published on docker hub on tag 8.3 ?

**Comment by mattrobenolt** [comment]
@LoicMahieu Yeah, I'll get this published today under `8.3.2`, `8.3`, and `8`.
