### ISSUE TITLE
MySql and remote redis

### ISSUE THREAD

**Issue by SUNNYANDPJ** [getsentry/docker-sentry#59]
If i wanna use remote and remote reids. What should i do for it.

**Comment by mattrobenolt** [comment]
You can't use it with MySQL unless you fork and modify yourself. Sentry does not support MySQL beginning with 8.0.

For Redis, you can set the environment variables, `SENTRY_REDIS_*`, which are labeled here: https://github.com/getsentry/docker-sentry/blob/master/8.3/sentry.conf.py#L10-L12 If you need something more complex, you're free to just plop in your own `sentry.conf.py` file and do whatever you want.

This image isn't intended to do 100% of all situations out of the box without modifications, so don't be afraid to add in your own config file if the default doesn't work out for you.
