### ISSUE TITLE
Add dumb-init

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/docker-sentry#64]
https://github.com/Yelp/dumb-init

**Comment by yosifkit** [comment]
You could also use https://github.com/krallin/tini. It even has signed releases. :heart:

I have not seen any important difference between them; both do requested task of reaping zombies and forwarding signals.  There are official images using each of them.

**Comment by mattrobenolt** [comment]
Thanks for weighing in @yosifkit! Mind pointing me to an official image that uses each so I can compare? I'll likely just pick one at random, just curious how the others are implemented.

**Comment by yosifkit** [comment]
Newly official [consul](https://github.com/hashicorp/docker-consul) uses `dumb-init` (through they pull it from their own build process with ["Docker Base"](https://github.com/hashicorp/docker-base/)).

[Kibana](https://github.com/docker-library/kibana) from a simple `tini` use case or [redmine](https://github.com/docker-library/redmine) for a more complex setup to only use `tini` when running passenger.

**Comment by mattrobenolt** [comment]
I used `tini` instead, and was merged in with #66
