### ISSUE TITLE
Celery beat docker container gives Exited (1) error

### ISSUE THREAD

**Issue by jtemporal** [getsentry/docker-sentry#76]
Hi guys,

I was following the "How to setup a full Sentry instance" documentation that can be found on docker hub and once I got through all the steps, I ran `docker ps -a` and noticed that the container named sentry-celery-beat had an "Exited (1)" in the STATUS column. 
When I took a look at the log for sentry-celery-beat container the last line of the traceback showed this: 
`celery.platforms.LockFailed: [Errno 17] File exists: '/celerybeat.pid'`

Is that an expected error?

Is worth mentioning that I can access sentry locally and the error is logged there.

**Comment by mattrobenolt** [comment]
Which version was this with?

**Comment by rougeth** [comment]
I got the same issue running all latest images.

**Comment by mattrobenolt** [comment]
Do you have a volume that's persisting this file? The only reason this would happen is if the pid file is found when the process starts back up. Which means it's being persisted between container restarts.

**Comment by rougeth** [comment]
I don't, actually I'm doing nothing different from the docs.

```
docker run -d --name sentry-redis redis
docker run -d --name sentry-postgres -e POSTGRES_PASSWORD=secret -e POSTGRES_USER=sentry postgres
docker run -it --rm -e SENTRY_SECRET_KEY='<secret-key>' --link sentry-postgres:postgres --link sentry-redis:redis sentry upgrade
docker run -d --name my-sentry -e SENTRY_SECRET_KEY='<secret-key>' --link sentry-redis:redis --link sentry-postgres:postgres sentry
docker run -d --name sentry-celery-beat -e SENTRY_SECRET_KEY='<secret-key>' --link sentry-postgres:postgres --link sentry-redis:redis sentry celery beat
docker run -d --name sentry-celery1 -e SENTRY_SECRET_KEY='<secret-key>' --link sentry-postgres:postgres --link sentry-redis:redis sentry celery worker
```
I tried on Ubuntu and OS X (didn't have docker installed).

**Comment by jtemporal** [comment]
Same thing as @rougeth all the latest images and no persisting volume.

**Comment by marksteve** [comment]
@rougeth @jtemporal Use `sentry run cron` instead

@mattrobenolt https://github.com/docker-library/docs/pull/602

**Comment by rougeth** [comment]
Just tested here. Worked fine! Thanks @marksteve. :+1:

**Comment by jtemporal** [comment]
It worked for me too! Thanks @marksteve :)

**Comment by mattrobenolt** [comment]
I guess this is worth noting. I'm not aware of why this would be broken for the older `sentry celery beat` command, but works fine with the new `sentry run cron`. In theory, the old should have been backwards compatible. I'll investigate, but not going to spend a ton of time unless it's blatantly obvious.
