### ISSUE TITLE
Allow specifying a Redis password

### ISSUE THREAD

**Issue by wernight** [getsentry/docker-sentry#78]
Some users have set up Redis with a password and it'd be useful to allow Sentry to work with those DB.

**Comment by wernight** [comment]
Looking at https://github.com/getsentry/sentry/issues/2530 it could be just adding a `SENTRY_REDIS_PASSWORD` in https://github.com/getsentry/docker-sentry/blob/902ac5c7e65aa0bfe891b6273b8693af704ccfde/8.5/sentry.conf.py under

    SENTRY_OPTIONS.update({
        'redis.clusters': {

**Comment by mattrobenolt** [comment]
I swear I thought I did this... I'll confirm and add it in today if not.

**Comment by mattrobenolt** [comment]
Yeah, I did: https://github.com/getsentry/docker-sentry/commit/58b6787ecb4cb30dea91ca8237117f228c86b65c

**Comment by wernight** [comment]
Oh yea. May be not yet released? https://hub.docker.com/_/sentry/ points to the version without it.

**Comment by mattrobenolt** [comment]
That's possible. A new release is happening tomorrow anyways, so it'll for sure go with that.

**Comment by matti** [comment]
@mattrobenolt  still without docs at https://hub.docker.com/_/sentry/
