### ISSUE TITLE
Document upgrade procedure

### ISSUE THREAD

**Issue by skydiver** [getsentry/docker-sentry#83]
I need to upgrade my current (docker) 8.5.1 installation to 8.6.0

I'm trying to define a list of steps to perform the upgrade.

I will start making a list and hope anyone can post comments / suggestions:
1. shutdown **worker**, **beat** and **main sentry** containers
2. _???_ run `$ docker pull sentry:onbuild`
3. _???_ perfom **database upgrade** running: `$ docker run -it --rm -e SENTRY_SECRET_KEY='<secret-key>' --link sentry-postgres:postgres --link sentry-redis:redis sentry upgrade`

I'm missing something else?

Thanks.-

**Comment by mattrobenolt** [comment]
> run $ docker pull sentry:onbuild ?

I'd pull a very specific version, like, `docker pull sentry:8.6.0-onbuild`.

but yeah, this basically covers it. You can alternatively always do `sentry run web --upgrade` which will run `upgrade` prior to starting up the web processes. You can set this to your `CMD` to make it the default behavior. It'll obviously make startup time a bit slower, but an `upgrade` is noop if there's nothing to do.

**Comment by mattrobenolt** [comment]
Also, I'll leave this open since it's worth officially documenting this process for docker setups.

**Comment by bdewater** [comment]
@skydiver did you run into any problems? I'm planning to upgrade this week.

**Comment by skydiver** [comment]
This was my final upgrade procedure:

Also, I'm using **docker-compose**.

1. `docker-compose stop` #stop all containers 
2. `docker pull sentry:8.6.0-onbuild` #pull specific image
3. `docker-compose build` #rebuild images
4. changed **docker-compose.yml** command from **sentry run web** to **sentry run web --upgrade**
5. restarted all containers because **beat** and **worker** has started before the upgrade command

Everything looks fine.

**Comment by ragesoss** [comment]
These were helpful instructions for me, upgrading from 8.20 to 8.21; something along those lines would make sense in the README for https://github.com/getsentry/onpremise.

**Comment by bikeshedder** [comment]
I just created an `update.sh` in my `onpremise` checkout as I kept forgetting the commands:

```
#!/bin/bash

set -e

git pull
docker-compose stop || true
docker pull sentry
docker-compose build
docker-compose run --rm web upgrade
docker-compose up -d
```

**Comment by viktorsmari** [comment]
Is there an official way that can be documented in the readme?

**Comment by hbokh** [comment]
And what about “bigger updates”, like going from 8.12 to 8.22? (Using the onbuild-image in my particular case.)

**Comment by toabi** [comment]
What @bikeshedder wrote worked for me to go from some 8.11 to 9.0 without hassle. :)

**Comment by macnibblet** [comment]
Since 8.22 doesn't have named volumes won't you lose the entire database/sentry files without modifying the volumes to use the local paths?

**Comment by alfredbez** [comment]
I'd like to upgrade our sentry installation from 9.0.0 to 9.1.2. Is [the script](https://github.com/getsentry/docker-sentry/issues/83#issuecomment-349337378) provided by @bikeshedder still working or should I do it like documented in the [on-premise readme](https://github.com/getsentry/onpremise/tree/263acda90b4bf3368066b07240eb03d11500c509#updating-sentry)?
> Use the following steps after updating this repository or your Dockerfile:
>```
>docker-compose build --pull # Build the services again after updating, and make sure we're up to >date on patch version
>docker-compose run --rm web upgrade # Run new migrations
>docker-compose up -d # Recreate the services
>```

**Comment by BYK** [comment]
@alfredbez  - They are almost the same, except the script is taking care of stopping your running containers for the upgrade.

Also, it is better to ask these types of questions over at [the forums](https://forum.sentry.io/c/on-premise) to leverage the experience of other community members.

**Comment by alfredbez** [comment]
@BYK thanks for the quick response, I just tried the script, but only after I set `SENTRY_IMAGE`.

I called it like so:
```
$ SENTRY_IMAGE=sentry:9.1 bash update.sh
```
First I saw a warning at the top of the sentry-backend:
> Celery workers are referencing a different version of Sentry

However, that disappeared after a minute or so.

**Comment by BYK** [comment]
@alfredbez feel free to report back if you see anything weird or broken :)

**Comment by BYK** [comment]
This is now covered over at the https://github.com/getsentry/onpremise repo with its `./install.sh` script. Any new issues should be reported there.
