### ISSUE TITLE
Changing TIMEZONE

### ISSUE THREAD

**Issue by nicolasteodosio** [getsentry/docker-sentry#84]
Hello, 
first of all thank you for the project.

Secondly I live in Brazil and here we're in a different timezone (UTC-3), but the default time zone for sentry is (UTC). There is a way to change that ?  If not how can I help to open a PR with this fix if it's relevant to the project

**Comment by sc-syf** [comment]
do U means the time at sentry web display ?

check this 

https://forum.sentry.io/t/a-setting-to-display-times-in-local-time-rather-than-utc/265

**Comment by pro100coder** [comment]
+1

**Comment by mattrobenolt** [comment]
Frankly, you shouldn't need to change this and will likely cause other issues. Your personal timezone as a user is a user's configuration option from the UI.
