### ISSUE TITLE
'symsynd is unavailable.  Install sentry with the dsym feature flag.')

### ISSUE THREAD

**Issue by unikulin** [getsentry/docker-sentry#87]
Lunch sentry from docker image.
When I try to upload dSym from Xcode sentry return 500 error
and in internal project rise issue:
RuntimeError: symsynd is unavailable.  Install sentry with the dsym feature flag.

**Comment by mattrobenolt** [comment]
We don't yet have support for dsyms in docker. Or for on-premise in general yet. It's massively difficult and are still working through how we do it ourselves on sentry.io. So in the meantime, this is unsupported for on-premise.
