### ISSUE TITLE
exim4 "relay not permitted"?

### ISSUE THREAD

**Issue by miracle2k** [getsentry/docker-sentry#89]
Seeing this when trying to send emails. 

Am I expected to configure the tianon/exim4 image futher? The instructions (https://docs.sentry.io/server/installation/docker/) that this is expected.

**Comment by mattrobenolt** [comment]
Using exim4 here is just merely an example. It'd be up to you to figure out what's needed in your environment to delivery email. Typically this is just an external email provider like SendGrid or Amazon SES where you just plug in SMTP credentials, rather than running your own mail server.
