### ISSUE TITLE
Test mail was sent, but email verification doesn't

### ISSUE THREAD

**Issue by mohamadx** [getsentry/docker-sentry#90]
Hi  
I did install sentry 8.9.0 based on https://hub.docker.com/_/sentry/ image  
I have an issue with sending emails, I was run docker and setup a remote SMPT server via environment variables. The test email was sent without any problem. But when I want to verify my email address, the verification email does not work and I don't catch any emails in my inbox.  
Also, I was run worker and cron container
By the way, I see #35 but it was not helpful for me.  
I think my sentry jobs does not work! base on below image:  
<img width="964" alt="screen shot 2016-10-16 at 18 49 07" src="https://cloud.githubusercontent.com/assets/15182195/19418475/68a0b6ca-93d1-11e6-9d71-2275b880d4b8.png">

**Comment by mohamadx** [comment]
@mattrobenolt Can you help me, please?

**Comment by mohamadx** [comment]
My issue has been fixed!

The email environment variables must be set on both `cron` and `worker` container like this:

```
docker run -d --name sentry-cron \
-e SENTRY_SECRET_KEY='<your secret>' \
-e SENTRY_EMAIL_HOST='example.com' \
-e SENTRY_EMAIL_PORT='25' \
-e SENTRY_EMAIL_USER='user@example.com' \
-e SENTRY_EMAIL_PASSWORD='<password>' \
-e SENTRY_SERVER_EMAIL='Sentry <user@example.com>'  \
--link sentry-postgres:postgres \
--link sentry-redis:redis sentry run cron
```
and 
```
docker run -d --name sentry-worker \
-e SENTRY_SECRET_KEY='<your secret>' \
-e SENTRY_EMAIL_HOST='example.com' \
-e SENTRY_EMAIL_PORT='25' \
-e SENTRY_EMAIL_USER='user@example.com' \
-e SENTRY_EMAIL_PASSWORD='<password>' \
-e SENTRY_SERVER_EMAIL='Sentry <user@example.com>'  \
--link sentry-postgres:postgres \
--link sentry-redis:redis sentry run worker
```

Thanks for this useful comment: [https://github.com/getsentry/docker-sentry/issues/40#issuecomment-178438188](https://github.com/getsentry/docker-sentry/issues/40#issuecomment-178438188)

**Please mark this issue as Resolved**

**Comment by Roberto34343** [comment]
Does it work with Gmail smtp server?

**Comment by mattrobenolt** [comment]
It should. There's no real reason it wouldn't, though I haven't personally tested.

**Comment by Roberto34343** [comment]
mattrobenolt 
I tried sentry with postfix and works great but with gmail smtp does not work.

docker run -d --name my-redis redis

docker run -d --name my-postgres -e POSTGRES_PASSWORD=secret -e POSTGRES_USER=sentry postgres

docker run -it --rm -e SENTRY_SECRET_KEY='secret key' --link my-postgres:postgres --link my-redis:redis sentry upgrade

docker run -d --name my-sentry  -e SENTRY_SECRET_KEY='secret key' -e SENTRY_SERVER_EMAIL=r.....k@gmail.com -e SENTRY_EMAIL_HOST=smtp.gmail.com -e SENTRY_EMAIL_PORT=587  -e SENTRY_EMAIL_USER=r.....k@gmail.com -e SENTRY_EMAIL_PASSWORD='*****' -e SENTRY_EMAIL_USE_TLS=True --link my-redis:redis --link my-postgres:postgres -p 8080:9000 sentry

docker run -d --name my-cron -e SENTRY_SECRET_KEY='secret key' -e SENTRY_SERVER_EMAIL=robercoek@gmail.com -e SENTRY_EMAIL_HOST=smtp.gmail.com -e SENTRY_EMAIL_PORT=587  -e SENTRY_EMAIL_USER=r.....k@gmail.com -e SENTRY_EMAIL_PASSWORD='*****' -e SENTRY_EMAIL_USE_TLS=True --link my-postgres:postgres --link my-redis:redis sentry run cron

docker run -d --name sentry-worker-1 -e SENTRY_SECRET_KEY='secret key' -e SENTRY_SERVER_EMAIL=robercoek@gmail.com -e SENTRY_EMAIL_HOST=smtp.gmail.com -e SENTRY_EMAIL_PORT=587  -e SENTRY_EMAIL_USER=r.....k@gmail.com -e SENTRY_EMAIL_PASSWORD='*****' -e SENTRY_EMAIL_USE_TLS=True --link my-postgres:postgres --link my-redis:redis sentry run worker

Also appears this **STARTTLS extension not supported by server** in the email config.

**Comment by deadlocks** [comment]
Gmail SMTP is not working for me too. 
![screenshot-52 203 165 82 9000-2016-12-11-17-13-40](https://cloud.githubusercontent.com/assets/2733405/21079872/833a93fa-bfc5-11e6-9b58-5e678a71a2f6.png)

@Roberto34343 Have you found any solution?

**Comment by Roberto34343** [comment]
@deadlocks make a issue and send me the link.

**Comment by deadlocks** [comment]
@Roberto34343 I have created a new issue #94

**Comment by zahirabbask** [comment]
@deadlocks please use port 587 instead of 465

**Comment by deadlocks** [comment]
@zahirabbask I can't ask IT to open 587 port so I am stuck here. But @Roberto34343 is using 587 port and still facing this issue #94

**Comment by zahirabbask** [comment]
@deadlocks you should use TSL for sentry. sentry is not supporting ssl. @Roberto34343 you should allow less secure app for you google account. first sign in to your google account then go through the link https://www.google.com/settings/security/lesssecureapps and click turn on.

**Comment by brunis** [comment]
My sendgrid is working, but only from the admin web interface. No member signup emails have arrived, despite resending and regenerating.

**Comment by Iprarthana** [comment]
how to configure for python installation. I did some changes 'config.yml'. but, it's not changed.
![screenshot from 2018-01-18 14-40-20](https://user-images.githubusercontent.com/35563977/35096323-c82c5324-fc71-11e7-9096-828b700ba429.png)
And also i didn't get verification email or even the test email. It shows '[Errno 111] Connection refused'.
What should I do for this problem?
