### ISSUE TITLE
Gmail SMTP Not Working 

### ISSUE THREAD

**Issue by deadlocks** [getsentry/docker-sentry#94]
Email is not working when configured with Gmail SMTP settings. I have used following variables.

SENTRY_SERVER_EMAIL
SENTRY_EMAIL_HOST
SENTRY_EMAIL_PORT
SENTRY_EMAIL_USER
SENTRY_EMAIL_PASSWORD
SENTRY_EMAIL_USE_TLS
SERVER_EMAIL

Using Sentry 8.11 on Ubuntu 14.04

![SMTP Gmail](https://cloud.githubusercontent.com/assets/2733405/21079872/833a93fa-bfc5-11e6-9b58-5e678a71a2f6.png)

**Comment by mattrobenolt** [comment]
There's nothing wrong with Sentry here. The error is saying that whatever connection credentials you're using are wrong. I'm not an expert with Gmail, but shouldn't the port be 587 for TLS?

**Comment by deadlocks** [comment]
@mattrobenolt Thanks for prompt reply. I am using same credentials in php and its working fine, and SSL/TLS encrypted SMTP uses port 465

I am not of much help here. If you could direct me in right direction then I can debug things on my own. From past discussions it looks like I should check Celery logs, but I am not sure how to access those logs.

And thanks Sentry. I really appreciate your efforts.

**Comment by mattrobenolt** [comment]
One thing to note: Sentry doesn't support SSL for email, only TLS. Port 465 is for SSL while 587 is for TLS.

**Comment by deadlocks** [comment]
Any idea if adding SSL support is in upcoming roadmap?

**Comment by mattrobenolt** [comment]
That's not happening unless we upgrade Django, which brings in SSL support, which likely isn't going to happen. Is there a problem here though? TLS is better and more supported than SSL anyways and is the recommended way.

**Comment by deadlocks** [comment]
No problem, just our it support is not comfortable with opening another port. Thanks for your help!!!! :+1:

**Comment by Roberto34343** [comment]
Im using TLS in the correct port 587 and the correct variables and it doesnt work.
![sentry](https://cloud.githubusercontent.com/assets/22382559/21192495/0205df42-c1e6-11e6-9a9a-76a57936c5e6.png)
