### ISSUE TITLE
Alternative easy Docker setup

### ISSUE THREAD

**Issue by eXistenZNL** [getsentry/docker-sentry#96]
### What

https://hub.docker.com/_/sentry/ notes under the header Contributing that it is a good idea if I opened an issue before I went off and started coding left and right, that's why you are reading this.

I created a setup method that is completed with a few commands by using a docker-compose.yml rather than starting individual docker containers.

### Why

I found it to be a bit tedious to set up Sentry using docker by following the original guide so I decided to make stuff a bit easier, and since open source is all about sharing I hope to do others a favour by sharing this as well.

### Link to the repo

https://github.com/eXistenZNL/easySentry

### Todo

Please let me know on how to proceed.
I can create a PR that adds the files I created to this repo and updates the setup guide if that's desired, or I could simply create a PR that adds a link to my repo in the official setup guide as a reference.

**Comment by mattrobenolt** [comment]
That's precisely what https://github.com/getsentry/onpremise is for.

This repository is entirely unopinionated and just provides the containers. It has no place for docker-compose, etc. This is, by nature, the primitive building block.

On the other hand, `onpremise` is our recommendation for where you'd start if you want to run your own server and has a few additional opinions, but not too much.

**Comment by eXistenZNL** [comment]
Ah, didn't know about the onpremise repo. Not bad, not bad :)

**Comment by eXistenZNL** [comment]
Come to think of it: shouldn't we include a link in the documentation? onpremise is a completely separated project that unless you heard of it, is not easily discovered.
