### ISSUE TITLE
Allow installation of additional libs

### ISSUE THREAD

**Issue by leo-labs** [getsentry/docker-sentry#99]
The onbuild docker image should allow installation of additional libs such as `libldap2-dev`. Otherwise plugins that depend on those libs cannot be installed via requirements.txt

**Comment by mattrobenolt** [comment]
Why can't you add `RUN apt-get install xxx`? This is just normal Docker stuff. There's nothing preventing you from installing whatever you want.

**Comment by leo-labs** [comment]
ONBUILD RUN if [ -s requirements.txt ]; then pip install -r requirements.txt; fi` runs before any other command (such as an `RUN apt-get`). Since at that point the libraries are not installed it will fail. The only solution is to not use the onbuild image. If this how the images are supposed to be used?

**Comment by mattrobenolt** [comment]
Yeah, this is very much a Docker limitation. Every `onbuild` package has these limitations and they're only intended to be a shortcut. See thing like, `python:onbuild` and whatnot. If you need to do these kids of things, just `FROM sentry:8` and copy/paste the few things you need that `onbuild` does.

**Comment by leo-labs** [comment]
Ok. Thanks for the clarification!
